# <center> Part A </center>

### 1) Import numpy as np, and pandas as pd

In [8]:
# your code here
import numpy as np
import pandas as pd

In [ ]:
# leave this cell blank

### 2) Re-implement the following logic in a single line of code with list comprehension

In [3]:
# original code
def foo(n):
    return n*(n-1)/2

lst = [10, 20, 30, 40, 50]

nlst = []
for l in lst:
    nlst.append(foo(l))

print (nlst)

[45.0, 190.0, 435.0, 780.0, 1225.0]


In [4]:
# your single line of code (not including print statement) using list comprehension here
nlst = [foo(l) for l in lst] # [n*(n-1)/2 for n in lst] is also possible
print (nlst)

[45.0, 190.0, 435.0, 780.0, 1225.0]


In [ ]:
# leave this cell blank

### 3) Re-implement the following logic in a single line of code with map and lambda

In [5]:
# original code
def foo(n):
    return n*(n-1)/2

lst = [10, 20, 30, 40, 50]

nlst = []
for l in lst:
    nlst.append(foo(l))

print (nlst)

[45.0, 190.0, 435.0, 780.0, 1225.0]


In [6]:
# your single line of code (not including print statement) using map and lambda here
nlst = list(map(lambda l: l*(l-1)/2, lst))
print (nlst)

[45.0, 190.0, 435.0, 780.0, 1225.0]


In [ ]:
# leave this cell blank

### 4) Re-implement the following logic in a single line of code with filter and lambda

In [1]:
# original code
def foo(n):
    if n>25:
        return True
    else:
        return False

lst = [10, 20, 30, 40, 50]

nlst = []
for l in lst:
    if foo(l) == True:
        nlst.append(l)

print (nlst)

[30, 40, 50]


In [2]:
# your single line of code (not including print statement) using filter and lambda here
nlst = list(filter(lambda l: l>25, lst))
print (nlst)

[30, 40, 50]


In [ ]:
# leave this cell blank

# <center> Part B </center>

### 5) Execute the next cell as-is to create a numpy array arr

In [9]:
np.random.seed(10)
arr = np.random.randint(1, 100, (1, 35))
print (arr)

[[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
  70 14 26 14 93 87 31 31 90 13 66]]


In [ ]:
# leave this cell blank

### 6) Re-shape arr to have 5 rows and 7 columns; then print arr 
##### [note: after this manipulation arr should have 5 rows and 7 columns]

In [10]:
# your code here
arr = np.reshape(arr, (5, 7))
print (arr)

[[10 16 65 29 90 94 30]
 [ 9 74  1 41 37 17 12]
 [55 89 63 34 73 79 50]
 [52 55 78 70 14 26 14]
 [93 87 31 31 90 13 66]]


In [ ]:
# leave this cell blank

### 7) Convert arr into a pandas dataframe called df with rows ['s1', 's2', 's3', 's4', 's5'] and columns ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']; then print df

In [11]:
# your code here
df = pd.DataFrame(arr, index=['s1', 's2', 's3', 's4', 's5'], columns=['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7'])
print (df)

    f1  f2  f3  f4  f5  f6  f7
s1  10  16  65  29  90  94  30
s2   9  74   1  41  37  17  12
s3  55  89  63  34  73  79  50
s4  52  55  78  70  14  26  14
s5  93  87  31  31  90  13  66


In [ ]:
# leave this cell blank

### 8) Include a new column called 'f8' in df with the following values: ['X', 'X', 'X', 'Y', 'Y']; then print df
##### [note: afer this manipulation df should contain a new column called f8]

In [12]:
# your code here
df['f8'] = ['X', 'X', 'X', 'Y', 'Y']
print (df)

    f1  f2  f3  f4  f5  f6  f7 f8
s1  10  16  65  29  90  94  30  X
s2   9  74   1  41  37  17  12  X
s3  55  89  63  34  73  79  50  X
s4  52  55  78  70  14  26  14  Y
s5  93  87  31  31  90  13  66  Y


In [ ]:
# leave this cell blank

### 9) Print column f1 in df

In [13]:
# your code here
print (df['f1'])

s1    10
s2     9
s3    55
s4    52
s5    93
Name: f1, dtype: int32


In [ ]:
# leave this cell blank

### 10) Print row s3 in df

In [21]:
# your code here
print (df.loc['s3'])

f1    55
f2    89
f3    63
f4    34
f5    73
f6    79
f7    50
f8     X
Name: s3, dtype: object


In [ ]:
# leave this cell blank

### 11) Print the element at row s4 and column f6 in df

In [22]:
# your code here
print (df.loc['s4']['f6'])

26


In [ ]:
# leave this cell blank

### 12) Print the subsection of data in df containing rows s2 and s3, and columns f5 and f6

In [24]:
# your code here
print (df.loc['s2':'s3', 'f5':'f6'])

    f5  f6
s2  37  17
s3  73  79


In [ ]:
# leave this cell blank

### 13) Create a new column in df called 'f9' as the sum of column 'f1' and column 'f2'; then print df
##### [note: afer this manipulation df should contain a new column called f9]

In [25]:
# your code here
df['f9'] = df['f1'] + df['f2']
print (df)

    f1  f2  f3  f4  f5  f6  f7 f8   f9
s1  10  16  65  29  90  94  30  X   26
s2   9  74   1  41  37  17  12  X   83
s3  55  89  63  34  73  79  50  X  144
s4  52  55  78  70  14  26  14  Y  107
s5  93  87  31  31  90  13  66  Y  180


In [ ]:
# leave this cell blank

### 14) Create a new column in df called 'f10' as the log of column 'f3'; then print df
##### [note: afer this manipulation df should contain a new column called f10]

In [26]:
# your code here
df['f10'] = np.log(df['f3'])
print (df)

    f1  f2  f3  f4  f5  f6  f7 f8   f9       f10
s1  10  16  65  29  90  94  30  X   26  4.174387
s2   9  74   1  41  37  17  12  X   83  0.000000
s3  55  89  63  34  73  79  50  X  144  4.143135
s4  52  55  78  70  14  26  14  Y  107  4.356709
s5  93  87  31  31  90  13  66  Y  180  3.433987


In [ ]:
# leave this cell blank

### 15) Create a new column in df called 'f11' as the standardized value of column 'f4'; then print df
##### [note: to standardize the elements in a column, you will subtract out the mean of the column, and divide by standard deviation of the column]
##### [note: afer this manipulation df should contain a new column called f11]

In [27]:
# your code here
df['f11'] = (df['f4'] - df['f4'].mean())/df['f4'].std()
print (df)

    f1  f2  f3  f4  f5  f6  f7 f8   f9       f10       f11
s1  10  16  65  29  90  94  30  X   26  4.174387 -0.712697
s2   9  74   1  41  37  17  12  X   83  0.000000  0.000000
s3  55  89  63  34  73  79  50  X  144  4.143135 -0.415740
s4  52  55  78  70  14  26  14  Y  107  4.356709  1.722350
s5  93  87  31  31  90  13  66  Y  180  3.433987 -0.593914


In [ ]:
# leave this cell blank

### 16) Use apply and lambda to create a new column in df called 'f12', where f12 is set to 1 if f5>50, else it is set to 0; then print df
##### [note: afer this manipulation df should contain a new column called f12]

In [28]:
# your code here
df['f12'] = df['f5'].apply(lambda x: 1 if x>50 else 0)
print (df)

    f1  f2  f3  f4  f5  f6  f7 f8   f9       f10       f11  f12
s1  10  16  65  29  90  94  30  X   26  4.174387 -0.712697    1
s2   9  74   1  41  37  17  12  X   83  0.000000  0.000000    0
s3  55  89  63  34  73  79  50  X  144  4.143135 -0.415740    1
s4  52  55  78  70  14  26  14  Y  107  4.356709  1.722350    0
s5  93  87  31  31  90  13  66  Y  180  3.433987 -0.593914    1


In [ ]:
# leave this cell blank

### 17) Drop columns f1, f2, f3, f4, f5 in df; then print df 
##### [note: after this manipulation, df should only contain columns f6 through f12]

In [29]:
# your code here
df.drop(['f1', 'f2', 'f3', 'f4', 'f5'], axis=1, inplace=True)
print (df)

    f6  f7 f8   f9       f10       f11  f12
s1  94  30  X   26  4.174387 -0.712697    1
s2  17  12  X   83  0.000000  0.000000    0
s3  79  50  X  144  4.143135 -0.415740    1
s4  26  14  Y  107  4.356709  1.722350    0
s5  13  66  Y  180  3.433987 -0.593914    1


In [ ]:
# leave this cell bblank

### 18) Use conditional selection and masking to only view those rows in df where f6 < f7 or f11 > 0
##### [note: you are NOT changing df as a result of this operation - just viewing the result of conditional selection with masking]

In [30]:
# your code here
print (df[(df['f6'] < df['f7']) | (df['f11'] > 0)])

    f6  f7 f8   f9       f10       f11  f12
s4  26  14  Y  107  4.356709  1.722350    0
s5  13  66  Y  180  3.433987 -0.593914    1


In [ ]:
# leave this cell blank

### 19) Use conditional selection and masking to only view those rows in df where f6 > f7 and f11 > 0
##### [note: you are NOT changing df as a result of this operation - just viewing the result of conditional selection with masking]

In [31]:
# your code here
print (df[(df['f6'] > df['f7']) & (df['f11'] > 0)])

    f6  f7 f8   f9       f10      f11  f12
s4  26  14  Y  107  4.356709  1.72235    0


In [ ]:
# leave this cell blank

### 20) Createa a pivot table to look at average values of f9 by features f8 and f12; also provide row averages and column averages

In [35]:
# your code here
#pd.pivot_table(df, values='f9', index=['f8', 'f12'], aggfunc=np.mean)
print (pd.pivot_table(df, values='f9', index=['f8', 'f12'], aggfunc={'f9': [np.mean, np.size]}))

         mean  size
f8 f12             
X  0     83.0   1.0
   1     85.0   2.0
Y  0    107.0   1.0
   1    180.0   1.0


In [36]:
# leave this cell blank